name: cache-restore-action
description: "Metti qualcosa in cache con differenziazione per repository automatica"
inputs:
  path:
    description: "Dati da prendere dalla cache"
    required: true
  dest:
    description: "Destinazione dei file"
    default: "."
    required: false
runs:
  using: "composite"
  steps:
    - run: '[ -f "/cache/${{ github.event.repository.name }}/${{ inputs.path }}" ] && cp -r "/cache/${{ github.event.repository.name }}/${{ inputs.path }}" ${{ inputs.dest }}'
      shell: bash