name: cache-restore-action
description: "Metti qualcosa in cache con differenziazione per repository automatica"
inputs:
  path:
    description: "Dati da mettere in cache"
    required: true
runs:
  using: "composite"
  steps:
    - run: "cp -r /cache/${{ github.event.repository.name }}/${{ inputs.path }} ."
      shell: bash