on:
  push:
    branches:
      - cache
jobs:
  test_action:
    runs-on: self-hosted
    name: "Test action"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Test action"
        uses: ./
        id: cache
        with:
          path: "test.txt"
      - name: "Check cached"
        run: |
          cat /cache/${{ github.event.repository.name }}/test.txt | grep 'successo' &> /dev/null
          if [ $? != 0 ]; then
             exit 1
          fi
        shell: bash