on:
  push:
    branches:
      - cache
jobs:
  test_action:
    runs-on: self-hosted
    name: "Test action"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Cache file"
        with:
          path: "test.txt"
      - name: "Check restored"
        run: |
          cat ./test.txt | grep 'successo' &> /dev/null
          if [ $? != 0 ]; then
             exit 1
          fi
        shell: bash